Fix virt-install disks typo
Fixes this traceback:

    Traceback (most recent call last):
      File "./virt-install", line 498, in <module>
        main()
      File "./virt-install", line 462, in main
        dom = guest.start_install(conscb,progresscb)
      File "/home/markmc/projects/virt/virtinst--devel/virtinst/Guest.py", line 813, in start_install
        return self._do_install(consolecb, meter)
      File "/home/markmc/projects/virt/virtinst--devel/virtinst/Guest.py", line 829, in _do_install
        self._create_devices(meter)
      File "/home/markmc/projects/virt/virtinst--devel/virtinst/Guest.py", line 725, in _create_devices
        disk.setup(progresscb)
    AttributeError: 'str' object has no attribute 'setup'

Looks to have been introduced by cset 351:07091304b759

Signed-off-by: Mark McLoughlin <markmc@redhat.com>